packages:
  - 'docs'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/config/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'